
def build(bld):
    # todo rename
#    bld.program(target = 'indexMapToOffsetMap', 
#            source = 'indexMapToOffsetMap.cpp', use = 'mrimage tclap kdtree kslicer')
#    
#    bld.program(target = 'applyDeform', 
#            source = 'applyDeform.cpp', use = 'mrimage tclap slicer')
#
    bld.program(target = 'niiHeader', 
            source = 'niiHeader.cpp', use = 'mrimage')

