
def build(bld):
    # todo rename
    bld.program(target = 'indexMapToOffsetMap', 
            source = 'indexMapToOffsetMap.cpp', use = 'mrimage tclap kdtree')

    bld.program(target = 'niiHeader', 
            source = 'niiHeader.cpp', use = 'mrimage')

