
def build(bld):
    bld.program(features='test', target = 'nifti_orient_test1', 
            source = 'nifti_orient_test1.cpp', use = 'mrimage')

    bld.program(features='test', target = 'nifti_orient_test2', 
            source = 'nifti_orient_test2.cpp', use = 'mrimage')

    bld.program(features='test', target = 'ndarray_accessor_test1', 
            source = 'ndarray_accessor_test1.cpp', use = 'ndarray')

    bld.program(features='test', target = 'coordinate_test1', 
            source = 'coordinate_test1.cpp', use = 'mrimage')

    bld.program(features='test', target = 'coordinate_test2', 
            source = 'coordinate_test2.cpp', use = 'mrimage')

    bld.program(target = 'nifti_rwrw_test', source = 'nifti_rwrw_test.cpp', use = 'mrimage')

    from waflib.Tools import waf_unit_test
    bld.add_post_fun(waf_unit_test.summary)
#    bld.program(target = 'test3', source = 'test3.cpp', use = 'mrimage')
#    bld.program(target = 'test4', source = 'test4.cpp', use = 'mrimage')
#    bld.program(target = 'nifti_test2', source = 'nifti_test2.cpp', use = 'mrimage')
#    bld.program(target = 'nifti_test3', source = 'nifti_test3.cpp', use = 'mrimage')
#    bld.program(target = 'slicer_test', source = 'slicer_test.cpp', use = 'slicer')
#    
#    bld.program(target = 'nl_store_test1', 
#                source = 'nl_store_test1.cpp', 
#                use = 'ndarray')
#    
#    bld.program(target = 'nl_store_test2', 
#                source = 'nl_store_test2.cpp', 
#                use = 'ndarray')
#    
#    bld.program(target = 'nl_store_test3', 
#                source = 'nl_store_test3.cpp', 
#                use = 'ndarray')
#    
#    bld.program(target = 'nl_store_test4', 
#                source = 'nl_store_test4.cpp', 
#                use = 'ndarray')
#    
#    bld.program(target = 'store_test1', source = 'store_test1.cpp', use = 'ndarray')
#    bld.program(target = 'store_test2', source = 'store_test2.cpp', use = 'ndarray')
#    bld.program(target = 'store_test3', source = 'store_test3.cpp', use = 'ndarray')
#    bld.program(target = 'store_test4', source = 'store_test4.cpp', use = 'ndarray') 
#    bld.program(target = 'matrix_test1', source = 'matrix_test1.cpp') 
#    bld.program(target = 'matrix_test2', source = 'matrix_test2.cpp') 
#    bld.program(target = 'matrix_test4', source = 'matrix_test4.cpp') 
#    bld.program(target = 'imgiter_test1', source = 'imgiter_test1.cpp', use='mrimage') 
#
#    bld(cmd = '${SRC[0]}', features = 'etest', 
#            source = ['slicer_test'], regex = 'PASS!')

