
def build(bld):
    bld(name = 'kdtree', export_includes = ['.'])
    bld(name = 'basic_functions', export_includes = ['.'])
    
    bld.shlib(target = 'registration',
            source = 'registration.cpp',
            use='mrimage mrimage_utils ndarray_utils accessors iterators lbfgs',
            export_includes = ['.'])
    bld.shlib(target = 'statistics',
            source = 'statistics.cpp',
            use='EIGEN',
            export_includes = ['.'])
    bld.shlib(target = 'utility',
            source = 'utility.cpp',
            use='EIGEN',
            export_includes = ['.'])
    bld.shlib(target = 'ndarray',
            source = 'ndarray.cpp', 
            use='npltypes slicer ZLIB',
            export_includes = ['.'])
    bld.shlib(target = 'ndarray_utils',
            source = 'ndarray_utils.cpp', 
            use='utility npltypes kslicer slicer chirpz ndarray FFTW',
            export_includes = ['.'])
    bld.shlib(target = 'slicer',
            source = 'slicer.cpp', 
            export_includes = ['.'])
    bld.shlib( target = 'kslicer',
            source = 'kernel_slicer.cpp', 
            export_includes = ['.'])
    bld.shlib( target = 'nplio', 
            source = 'nplio.cpp', 
            export_includes = ['.'],
            use='ZLIB mrimage ndarray') 
    bld.shlib( target = 'mrimage', 
            source = 'mrimage.cpp', 
            export_includes = ['.'],
            use='ndarray slicer EIGEN') 
    bld.shlib( target = 'mrimage_utils', 
            source = 'mrimage_utils.cpp', 
            export_includes = ['.'],
            use='mrimage iterators ndarray_utils fftw') 
#    bld.shlib( target = 'fractfft', 
#            source = 'fract_fft.cpp ', 
#            export_includes = ['.'],
#            use='FFTW utility basic_plot')
    bld.shlib( target = 'npltypes', 
            source = 'npltypes.cpp ', 
            export_includes = ['.'],
            use = 'EIGEN')
    bld.shlib( target = 'iterators', 
            source = 'iterators.cpp', 
            use='ndarray slicer kslicer',
            export_includes = ['.'])
    bld.shlib( target = 'basic_plot', 
            source = 'basic_plot.cpp', 
            export_includes = ['.'])
    bld.shlib( target = 'chirpz', 
            source = 'chirpz.cpp', 
            use = 'basic_plot FFTW',
            export_includes = ['.'])

